// Background service worker for SMS Assistant extension

console.log('SMS Assistant service worker loaded');
try {
  importScripts('../utils/schema.js');
} catch (e) {
  console.error('Failed to load schema utils:', e);
}

const BACKEND_URL = 'http://localhost:3000';
const PYTHON_SERVICE_URL = 'http://localhost:8000'; // Python FastAPI service

// Listen for messages from popup
let pendingPDFResolutions = new Map(); // tabId -> resolve function

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  console.log('Service worker received message:', request);

  if (request.action === 'fetchStudies') {
    handleFetchStudies(sendResponse);
    return true;
  }

  if (request.action === 'addSource') {
    handleAddSource(request.data, sendResponse);
    return true;
  }

  if (request.action === 'resolvePDFUrl') {
    // Content script is asking us to watch for a PDF URL redirect
    // generated by an iframe it just created
    if (sender.tab) {
      console.log(`Watching for PDF redirect in tab ${sender.tab.id}...`);
      // We'll wait up to 15s for the redirect to happen
      const promise = new Promise((resolve) => {
        pendingPDFResolutions.set(sender.tab.id, resolve);
        setTimeout(() => {
          if (pendingPDFResolutions.has(sender.tab.id)) {
            pendingPDFResolutions.delete(sender.tab.id);
            resolve(null); // Timed out
          }
        }, 15000);
      });

      promise.then(url => sendResponse({ url }));
      return true; // async
    }
  }

  if (request.action === 'checkDuplicate') {
    handleCheckDuplicate(request.data, sendResponse);
    return true;
  }

  if (request.action === 'attachPdf') {
    handleAttachPdf(request.data, sendResponse);
    return true;
  }
});

// Intercept specific S3 redirects
chrome.webRequest.onBeforeRequest.addListener(
  (details) => {
    // If we see a request to the assets domain, it's likely our PDF
    if (details.url.includes('sciencedirectassets.com') && details.url.includes('.pdf')) {
      if (details.tabId !== -1 && pendingPDFResolutions.has(details.tabId)) {
        console.log('Intercepted S3 PDF URL:', details.url);
        const resolve = pendingPDFResolutions.get(details.tabId);
        pendingPDFResolutions.delete(details.tabId);
        resolve(details.url);
      }
    }
  },
  { urls: ["*://*.sciencedirectassets.com/*"] }
);

/**
 * Fetch studies from backend
 */
async function handleFetchStudies(sendResponse) {
  try {
    const response = await fetch(`${BACKEND_URL}/api/studies`);

    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    const data = await response.json();
    sendResponse({ success: true, studies: data.data || [] });
  } catch (error) {
    console.error('Error fetching studies:', error);
    sendResponse({
      success: false,
      error: 'Failed to fetch studies. Make sure the backend is running at localhost:3000'
    });
  }
}

/**
 * Get page content from a tab
 * @param {number} tabId - Tab ID
 * @returns {Promise<string>} Page content
 */
async function getPageContent(tabId) {
  return new Promise((resolve) => {
    chrome.tabs.sendMessage(
      tabId,
      { action: 'getPageContent' },
      (response) => {
        if (chrome.runtime.lastError || !response) {
          console.warn('Failed to get page content:', chrome.runtime.lastError);
          resolve('');
          return;
        }
        resolve(response.content || '');
      }
    );
  });
}

/**
 * Extract authors using Python LLM service
 * @param {string} url - Page URL
 * @param {string} title - Page title
 * @param {string} pageContent - Page content
 * @returns {Promise<Object>} Authors and confidence
 */
async function extractAuthorsWithLLM(url, title, pageContent) {
  try {
    console.log('Calling Python LLM service for author extraction...');
    const response = await fetch(`${PYTHON_SERVICE_URL}/api/extract-authors`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        url: url,
        page_content: pageContent,
        title: title
      })
    });

    if (!response.ok) {
      console.warn('LLM author extraction failed:', response.status);
      return { authors: [], confidence: 'low' };
    }

    const data = await response.json();
    console.log('LLM extraction result:', data);
    return data;
  } catch (error) {
    console.error('Error calling LLM service:', error);
    return { authors: [], confidence: 'low' };
  }
}

/**
 * Add source to study (with PDF download if needed)
 */
// Request deduplication
const processingAdds = new Set();

/**
 * Add source to study (with PDF download if needed)
 */
async function handleAddSource(data, sendResponse) {
  const { studyId, metadata } = data;
  const dedupKey = `${studyId}:${metadata.url || metadata.title}`;

  if (processingAdds.has(dedupKey)) {
    console.warn('Ignoring duplicate add request for:', dedupKey);
    return;
  }

  processingAdds.add(dedupKey);

  try {
    // Step 1: Download PDF if URL is provided
    let pdfBlob = null;
    if (metadata.pdfUrl) {
      try {
        console.log('Downloading PDF from:', metadata.pdfUrl);
        pdfBlob = await downloadPDF(metadata.pdfUrl);
        console.log('PDF downloaded successfully, size:', pdfBlob.size);
      } catch (pdfError) {
        console.warn('Failed to download PDF:', pdfError);
        // Continue without PDF - we'll still save the metadata
      }
    }

    // Step 1.5: Check if we need LLM fallback for author extraction
    if ((!metadata.authors || metadata.authors.length === 0) && metadata.title) {
      console.log('No authors found, attempting LLM extraction...');
      try {
        // Need to get the current tab to extract page content
        const tabs = await chrome.tabs.query({ active: true, currentWindow: true });
        if (tabs.length > 0) {
          const pageContent = await getPageContent(tabs[0].id);
          if (pageContent) {
            const llmResult = await extractAuthorsWithLLM(
              metadata.url,
              metadata.title,
              pageContent
            );

            if (llmResult.authors && llmResult.authors.length > 0) {
              console.log('LLM extracted authors:', llmResult.authors);
              metadata.authors = llmResult.authors;
            }
          }
        }
      } catch (error) {
        console.warn('LLM author extraction failed:', error);
        // Continue without authors - validation will catch this
      }
    }

    // Step 2: Prepare FormData
    const formData = new FormData();

    // Determine source type (lowercase as expected by backend)
    const sourceType = pdfBlob ? 'pdf' : 'url';

    // Add PDF file if downloaded
    if (pdfBlob) {
      const filename = getFilename(metadata.pdfUrl, metadata.title);
      formData.append('file', pdfBlob, filename);
    }

    // Prepare metadata object
    // Use shared schema to ensure all fields are included
    const metadataToSend = {};

    // Base fields expected by backend schema
    // We map from our allowed fields to what we want to send
    // (In this case, we send everything that is allowed and present)
    if (typeof self.ALLOWED_METADATA_FIELDS !== 'undefined') {
      self.ALLOWED_METADATA_FIELDS.forEach(field => {
        if (metadata[field] !== undefined && metadata[field] !== null) {
          metadataToSend[field] = metadata[field];
        }
      });
    } else {
      // Fallback if import failed (should not happen if manifest correct, but strictly for SW)
      console.warn('Metadata schema not loaded, using fallback');
      Object.assign(metadataToSend, metadata);
    }

    // Ensure overrides/defaults
    metadataToSend.sourceType = sourceType;
    if (!metadataToSend.title) metadataToSend.title = 'Untitled';
    if (!metadataToSend.sourceCategory) metadataToSend.sourceCategory = 'GREY';

    // Remove pdfUrl from metadata payload (it's handled via file upload)
    delete metadataToSend.pdfUrl;

    // DEBUG: Log what we're sending
    console.log('=== DEBUG: Sending to backend ===');
    console.log('Metadata to send:', JSON.stringify(metadataToSend, null, 2));
    console.log('Has PDF file:', !!pdfBlob);
    console.log('================================');

    // Add metadata as JSON string
    formData.append('metadata', JSON.stringify(metadataToSend));

    // Step 3: Upload to backend
    console.log('Uploading to backend:', `${BACKEND_URL}/api/studies/${studyId}/sources/add`);
    const response = await fetch(`${BACKEND_URL}/api/studies/${studyId}/sources/add`, {
      method: 'POST',
      body: formData
    });

    if (!response.ok) {
      const errorData = await response.json();
      console.error('=== DEBUG: Backend error response ===');
      console.error('Status:', response.status);
      console.error('Error data:', JSON.stringify(errorData, null, 2));
      console.error('====================================');
      throw new Error(errorData.error || `HTTP error! status: ${response.status}`);
    }

    const result = await response.json();
    console.log('Source added successfully:', result);

    sendResponse({
      success: true,
      source: result.data,
      hadPDF: !!pdfBlob
    });
  } catch (error) {
    console.error('Error adding source:', error);
    sendResponse({
      success: false,
      error: error.message || 'Failed to add source to study'
    });
  } finally {
    processingAdds.delete(dedupKey);
  }
}

/**
 * Check if source exists in study
 */
async function handleCheckDuplicate(data, sendResponse) {
  const { studyId, metadata } = data;

  try {
    const response = await fetch(`${BACKEND_URL}/api/studies/${studyId}/sources/check-duplicate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        title: metadata.title,
        doi: metadata.doi,
        authors: metadata.authors
      })
    });

    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    const result = await response.json();
    sendResponse({ success: true, ...result }); // e.g. { success: true, exists: true/false, ... }
  } catch (error) {
    console.error('Error checking duplicate:', error);
    sendResponse({ success: false, error: 'Failed to check duplication status' });
  }
}

/**
 * Attach PDF to existing source
 */
async function handleAttachPdf(data, sendResponse) {
  const { studyId, sourceId, pdfUrl } = data;

  try {
    // Step 1: Download PDF
    console.log('Downloading PDF to attach from:', pdfUrl);
    let pdfBlob = null;
    try {
      pdfBlob = await downloadPDF(pdfUrl);
    } catch (e) {
      throw new Error('Failed to download PDF: ' + e.message);
    }

    // Step 2: Upload to backend
    const formData = new FormData();
    const filename = getFilename(pdfUrl, 'attached-source');
    formData.append('file', pdfBlob, filename);

    const response = await fetch(`${BACKEND_URL}/api/studies/${studyId}/sources/${sourceId}/upload-pdf`, {
      method: 'POST',
      body: formData
    });

    if (!response.ok) {
      const errorText = await response.text();
      let errorMsg = `HTTP error! status: ${response.status}`;
      try {
        const errorJson = JSON.parse(errorText);
        if (errorJson.error) errorMsg = errorJson.error;
      } catch (e) { /* ignore JSON parse error */ }

      throw new Error(errorMsg);
    }

    const result = await response.json();
    sendResponse({ success: true, data: result });

  } catch (error) {
    console.error('Error attaching PDF:', error);
    sendResponse({ success: false, error: error.message || 'Failed to attach PDF' });
  }
}

/**
 * Download PDF from URL
 * @param {string} url - PDF URL
 * @returns {Promise<Blob>} PDF blob
 */
async function downloadPDF(url) {
  // Try to download via the active tab/content script first (to share cookies/session)
  try {
    const tabs = await chrome.tabs.query({ active: true, currentWindow: true });
    if (tabs.length > 0) {
      console.log('Requesting PDF fetch from content script (tab ' + tabs[0].id + ')...');
      const response = await new Promise((resolve) => {
        chrome.tabs.sendMessage(
          tabs[0].id,
          { action: 'fetchPDF', url: url },
          (res) => resolve(res)
        );
      });

      if (response && response.success && response.data) {
        console.log('PDF fetched via content script!');
        // Convert base64 data URL to Blob
        return await (await fetch(response.data)).blob();
      } else {
        console.warn('Content script PDF fetch failed:', response ? response.error : 'No response');
      }
    }
  } catch (e) {
    console.warn('Error downloading via content script, falling back to direct fetch:', e);
  }

  // Fallback to direct fetch (background script context)
  console.log('Falling back to background fetch for PDF...');
  const response = await fetch(url);

  if (!response.ok) {
    throw new Error(`Failed to download PDF: ${response.status}`);
  }

  const blob = await response.blob();

  // Verify it's a PDF
  if (!blob.type.includes('pdf') && !url.toLowerCase().includes('.pdf')) {
    console.warn('Downloaded file may not be a PDF:', blob.type);
  }

  return blob;
}

/**
 * Get filename from URL or title
 * @param {string} url - PDF URL
 * @param {string} title - Paper title
 * @returns {string} Filename
 */
function getFilename(url, title) {
  try {
    const urlObj = new URL(url);
    const pathname = urlObj.pathname;
    const filename = pathname.split('/').pop();

    if (filename && filename.endsWith('.pdf')) {
      return filename;
    }
  } catch (e) {
    // URL parsing failed
  }

  // Fallback to title-based filename
  if (title) {
    const safe = title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .substring(0, 100);
    return `${safe}.pdf`;
  }

  return 'paper.pdf';
}

console.log('SMS Assistant service worker ready');

