"""Shared structured schemas for LLM responses."""

from .classification import (
    CLASSIFICATION_JSON_SCHEMA,
    CLASSIFICATION_RESPONSE_FORMAT,
    CLASSIFICATION_SCHEMA_NAME,
)
from .metadata import (
    METADATA_JSON_SCHEMA,
    METADATA_RESPONSE_FORMAT,
    METADATA_SCHEMA_NAME,
)

__all__ = [
    "METADATA_SCHEMA_NAME",
    "METADATA_JSON_SCHEMA",
    "METADATA_RESPONSE_FORMAT",
    "CLASSIFICATION_SCHEMA_NAME",
    "CLASSIFICATION_JSON_SCHEMA",
    "CLASSIFICATION_RESPONSE_FORMAT",
]
